name: Pull request checks

on:
  pull_request:
    push:
      branches:
        - main

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      - name: 游닌 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 游닌 Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.0

      - name: 游닌Install dependencies
        # There is a bug with lockfile generation when using package overrides, so for now we
        # install without the lockfile. :(
        # run: bun install --frozen-lockfile
        run: bun install

      - name: 游닌 Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt clippy
          target: wasm32-wasip1 wasm32-unknown-unknown

      - name: 游늶 Check formatting Biome
        run: bunx biome check .

      - name: 游늶 Check formatting Rust
        run: make fmt-check

      - name: 游늶 Clippy Check
        run: make check

      - name: 游댣 Build projects
        run: bun run build

      - name: 游빍 Run integration tests
        run: bun run test
