name: Pull request checks
on:
  pull_request:
    push:
      branches:
        - main

jobs:
  verify_build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.13

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check formatting
        run: bunx biome check .

      - name: Build projects
        run: bun run build

      - name: Run unit tests
        run: bun run test
