name: Deploy docs
on:
  push:
    branches:
      - main

jobs:
  verify_build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.0

      - name: 📥Install dependencies
        # There is a bug with lockfile generation when using package overrides, so for now we
        # install without the lockfile. :(
        # run: bun install --frozen-lockfile
        run: bun install

      - name: 📥 Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt clippy
          target: wasm32-wasip1 wasm32-unknown-unknown

      - name: 🔨 Build projects
        run: bun run build

      - name: 🧪 Run unit tests
        run: bun run test

      - name: 📄 Setup Pages
        uses: actions/configure-pages@v5

      - name: 📚 Create docs
        run: bun run docs

      - name: 🆙 Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./docs"

      - name: 📄 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
